# Generated by Django 6.0.5 on 2026-05-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('picture', models.CharField(default='https://dynamic-media-cdn.tripadvisor.com/media/photo-o/32/31/12/01/brilliant-for-night-views.jpg?w=1400&h=-1&s=1', max_length=200)),
                ('cuisine', models.CharField(max_length=200)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
